/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassGroup = IDL.Record({
  'members' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'countryCode' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatConversation = IDL.Record({
  'contact' : IDL.Text,
  'lastMessage' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClassGroup' : IDL.Func([ClassGroup], [], []),
  'addJob' : IDL.Func([JobListing], [], []),
  'addOrUpdateChat' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChat' : IDL.Func([IDL.Text], [], []),
  'deleteClassGroup' : IDL.Func([IDL.Text], [], []),
  'deleteJob' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChats' : IDL.Func([], [IDL.Vec(ChatConversation)], ['query']),
  'getClassGroups' : IDL.Func([], [IDL.Vec(ClassGroup)], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassGroup = IDL.Record({
    'members' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'countryCode' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const ChatConversation = IDL.Record({
    'contact' : IDL.Text,
    'lastMessage' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClassGroup' : IDL.Func([ClassGroup], [], []),
    'addJob' : IDL.Func([JobListing], [], []),
    'addOrUpdateChat' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChat' : IDL.Func([IDL.Text], [], []),
    'deleteClassGroup' : IDL.Func([IDL.Text], [], []),
    'deleteJob' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChats' : IDL.Func([], [IDL.Vec(ChatConversation)], ['query']),
    'getClassGroups' : IDL.Func([], [IDL.Vec(ClassGroup)], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };